services:
  - type: web
    name: iosoccer-apuestas-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PRODUCTION_URL
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
    healthCheckPath: /
